### ISSUE TITLE
Typo - dialgoflowSessionClient

### ISSUE THREAD

**Issue by reyerm** [GoogleCloudPlatform/dialogflow-integrations#1]
dialgoflowSessionClient i.s.o. dialogflowSessionClient in Skype library
e.g line 37 of Skype/server.js :
"const sessionClient = new dialgoflowSessionClient(projectId);"

**Comment by tyhu-google** [comment]
Thanks for pointing out reyerm@, we've updated a new patch to fix the typo.

**Comment by reyerm** [comment]
Thanks!
