### ISSUE TITLE
high latency of detectintent

### ISSUE THREAD

**Issue by TharakaSl** [GoogleCloudPlatform/dialogflow-integrations#20]
I am testing viberbot, key file is set to environment. 
I am using ngrok for test chat bot in local.

The issue is when calling detectIntent it will take nearly 8 seconds to get seponse.
`const answer = (await sessionClient.detectIntent(message.text, sessionId, message))`
Any reason for this ?

**Comment by tyhu-google** [comment]
Thanks for reporting the issue. TharakaSl@, have you tried to test it with Dialogflow Console for the same request, if so, how long does it take?
