### ISSUE TITLE
In a chatbot conversation using dialogflow cx, Is there a way to make the bot speak first?

### ISSUE THREAD

**Issue by jingliangjl** [GoogleCloudPlatform/dialogflow-integrations#230]
Hi,

I am building a chatbot using DialogFlow cx. The integrations I want to use are Dialogflow messenger and Google chat.

Need to have my bot to initiate the conversation before user types a message. It would something like welcome message as soon as user clicks on Bot icon. 

Hoping that anyone here can help with this(Both dialogflow messenger and google chat)

Thanks

**Comment by yahui-1002** [comment]
https://stackoverflow.com/questions/51184134/in-a-chatbot-conversation-using-dialogflow-is-there-a-way-to-make-the-bot-speak

**Comment by jingliangjl** [comment]
Thanks, I have asking help through Cloud community, I'll close the issue.
