### ISSUE TITLE
Question about billing account

### ISSUE THREAD

**Issue by moyado** [GoogleCloudPlatform/dialogflow-integrations#24]
I have a question about the integration of twilio with dialogflow. In the instructions they ask me to activate a billing account .
If I activate it ... They will charge money only if I reach the quotas? 
Can I still use the free service if I enable the billing account?

Thanks.

**Comment by tyhu-google** [comment]
moyado@, there might be two scenarios Google Cloud may ask you to activate a billing account. 1. Deploy you twilio server with CloudRun or other instances. 2. Upgrade your Dialogflow account to Enterprise tier.
In case 1, they will charge you when you CloudRun instance is running. In case 2. if you don't upgrade your account to enterprise tier, you shouldn't be charged.
