### ISSUE TITLE
Dialogflow send empty response to twilio when a new conversation is started

### ISSUE THREAD

**Issue by Neisser** [GoogleCloudPlatform/dialogflow-integrations#47]
HelloWorld, I'm having an issue with dialogflow, it is sending empty responses to twilio when a new conversation start. Im getting the error  **Warning - 14103 Invalid Body** in the twilio debugger. 

- Im sure the webhook is sending a response to dialogflow but dialogflow is sending an empty response to twilio. 
- The request takes less than one second
- Dialogflow bot send rigth answers after the third interaction

![image](https://user-images.githubusercontent.com/19783776/90525283-b33eae80-e134-11ea-8221-84e697c5354e.png)

this is an example of how im sending the responses from the webhook

![image](https://user-images.githubusercontent.com/19783776/90525673-20524400-e135-11ea-9558-f1b9f8dfb3e3.png)

**Comment by bptdeveloper** [comment]
I have exactly the same problem. Anybody can help us?
Thank you in advance!
